# テストデータ生成ツール設定ファイル

# テンプレート設定
templates:
  # タイトルのテンプレート
  # {date}: 日付
  # {weather}: 天気
  titles:
    - "日記 - {date}"
    - "{weather}の一日"
    - "今日の記録 - {date}"
    - "{date}の振り返り"

  # 内容のテンプレート
  # {activity}: 活動内容
  # {feeling}: 気分
  contents:
    - "今日は{activity}をした。{feeling}一日だった。"
    - "{activity}に取り組んだ。とても{feeling}。"
    - "今日の主な活動は{activity}。{feeling}時間を過ごせた。"
    - "{activity}を中心に過ごした一日。全体的に{feeling}。"

  # メモ用のテンプレート
  notes:
    # 天気のバリエーション
    weather:
      - "晴れ"
      - "曇り"
      - "雨"
      - "雪"
      - "晴れのち曇り"
      - "曇りのち雨"
      - "雨のち晴れ"

    # 気分のバリエーション
    feeling:
      - "楽しい"
      - "充実した"
      - "疲れた"
      - "やる気に満ちた"
      - "リラックスした"
      - "少し物足りない"
      - "達成感のある"

  # 活動項目のリスト
  items:
    - "運動"
    - "読書"
    - "勉強"
    - "仕事"
    - "趣味"
    - "家事"
    - "散歩"
    - "料理"
    - "プログラミング"
    - "映画鑑賞"

# 生成設定
generation:
  # デフォルトの生成率（1-100%）
  default_rate: 100

  # デフォルトの活動項目数（0以上）
  default_items_per_entry: 3

  # 生成データの出力ディレクトリ
  output_dir: "data"

# データベース設定
database:
  # 削除前のバックアップ作成
  backup_before_clear: true

  # バックアップディレクトリ
  backup_dir: "backups"

  # バックアップの保持期間（日数）
  backup_keep_days: 30

# ログ設定
logging:
  # ログレベル（DEBUG, INFO, WARNING, ERROR, CRITICAL）
  level: "INFO"

  # ログのフォーマット
  format: "%(asctime)s - %(levelname)s - %(message)s"

  # 日時フォーマット
  datefmt: "%Y/%m/%d %H:%M:%S"

  # ログファイル
  file: "logs/test_data.log"

# 活動項目の詳細テンプレート
item_templates:
  # 活動時間（分）の範囲
  duration:
    min: 15
    max: 120

  # 活動結果のバリエーション
  results:
    - "良い運動になりました"
    - "集中して取り組めました"
    - "充実した時間でした"
    - "とても楽しかったです"
    - "良い気分転換になりました"

  # 活動の印象
  impressions:
    - "とても有意義でした"
    - "新しい発見がありました"
    - "良い経験になりました"
    - "次回も続けたいです"
    - "もっと深めていきたいです"

  # 活動コメント
  comments:
    - "継続は力なりを実感しました"
    - "日々の積み重ねが大切だと感じました"
    - "良い習慣になってきました"
    - "今後も続けていきたいです"
    - "少しずつ上達を感じます"
